apiVersion: v2
name: my-prometheus-helm
description: A Helm chart for Prometheus Demo
type: application
version: 1.0.0

dependencies:
  - name: "prometheus"
    alias: prometheus
    condition: prometheus.enabled
    repository: "https://prometheus-community.github.io/helm-charts"
    version: "25.19.1"