apiVersion: v1
kind: Namespace
metadata:
  name: dev-environment
  labels:
    name: dev-environment
---
apiVersion: v1
kind: Namespace
metadata:
  name: uat-environment
  labels:
    name: uat-environment