apiVersion: v2
name: my-loki-helm
description: A Helm chart for Loki Demo
type: application
version: 1.0.0

dependencies:
  - name: "loki-stack"
    alias: loki
    condition: loki-stack.enabled
    repository: "https://grafana.github.io/helm-charts"
    version: "2.10.2"