apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-only-role
  namespace: dev-environment
rules:
- apiGroups:
  - ""
  - apps
  resources:
  - "*"
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-only-rolebinding
  namespace: dev-environment
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view-only-role
subjects:
- kind: ServiceAccount
  name: viewer
  namespace: default