apiVersion: v1
kind: ServiceAccount
metadata:
  name: viewer
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: viewer-secret
  namespace: default
  annotations:
    kubernetes.io/service-account.name: viewer
type: kubernetes.io/service-account-token
