version: '3.7'
services:
  jenkins:
    image: my-jenkins
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5555:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock